### ISSUE TITLE
Typo sometimes VERILIB sometimes VERLIB

### ISSUE THREAD

**Issue by theshadowx** [jkff90/verification#1]
in the scripts sometimes the environment variable used is VER**I**LIB sometimes it's VERLIB.

Which make the compilation to fail.

**Comment by anphambk** [comment]
Hi, thank you for your contribution and I am sorry for my late reply. I was busy during the weekdays.
I fixed the typos and updated to uvm-1.2 framework. I don't have a linux system to test the new code, just tested with cygwin on window. The compilation is ok, but I couldn't test the simulation since I don't have a personal license. I will test it later with the IUS.
Again, thank you.
